"""create core schema

Revision ID: f4dbe2a9b664
Revises: 
Create Date: 2026-09-03 17:53:35.906821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4dbe2a9b664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'approver', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('expense_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'paid', name='report_status'), server_default='draft', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_range_end >= date_range_start', name='ck_report_date_range_ordered'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_reports_is_archived'), 'expense_reports', ['is_archived'], unique=False)
    op.create_index(op.f('ix_expense_reports_owner_id'), 'expense_reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_expense_reports_status'), 'expense_reports', ['status'], unique=False)
    op.create_index('ix_expense_reports_status_submitted_at', 'expense_reports', ['status', 'submitted_at'], unique=False)
    op.create_table('expense_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('travel', 'lodging', 'meals', 'transportation', 'supplies', 'other', name='expense_category'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expense_line_amount_positive'),
    sa.CheckConstraint('length(btrim(description)) > 0', name='ck_expense_line_has_description'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_lines_category'), 'expense_lines', ['category'], unique=False)
    op.create_index(op.f('ix_expense_lines_report_id'), 'expense_lines', ['report_id'], unique=False)
    op.create_table('report_approvers',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'approver_id')
    )
    op.create_index('ix_report_approvers_approver_id', 'report_approvers', ['approver_id'], unique=False)
    op.create_table('report_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(body)) > 0', name='ck_report_comment_not_empty'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_comments_report_id_created_at', 'report_comments', ['report_id', 'created_at'], unique=False)
    op.create_table('report_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'paid', name='report_status'), nullable=False),
    sa.Column('to_status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'paid', name='report_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_events_created_at'), 'report_events', ['created_at'], unique=False)
    op.create_index('ix_report_events_report_id_created_at', 'report_events', ['report_id', 'created_at'], unique=False)
    op.create_table('stale_alert_dismissals',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'approver_id')
    )
    op.create_index('ix_stale_alert_dismissals_approver_id', 'stale_alert_dismissals', ['approver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stale_alert_dismissals_approver_id', table_name='stale_alert_dismissals')
    op.drop_table('stale_alert_dismissals')
    op.drop_index('ix_report_events_report_id_created_at', table_name='report_events')
    op.drop_index(op.f('ix_report_events_created_at'), table_name='report_events')
    op.drop_table('report_events')
    op.drop_index('ix_report_comments_report_id_created_at', table_name='report_comments')
    op.drop_table('report_comments')
    op.drop_index('ix_report_approvers_approver_id', table_name='report_approvers')
    op.drop_table('report_approvers')
    op.drop_index(op.f('ix_expense_lines_report_id'), table_name='expense_lines')
    op.drop_index(op.f('ix_expense_lines_category'), table_name='expense_lines')
    op.drop_table('expense_lines')
    op.drop_index('ix_expense_reports_status_submitted_at', table_name='expense_reports')
    op.drop_index(op.f('ix_expense_reports_status'), table_name='expense_reports')
    op.drop_index(op.f('ix_expense_reports_owner_id'), table_name='expense_reports')
    op.drop_index(op.f('ix_expense_reports_is_archived'), table_name='expense_reports')
    op.drop_table('expense_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
